find_path(SDL2_INCLUDE_DIR SDL2/SDL.h)
find_library(SDL2_LIBRARY NAMES SDL2 libSDL2)
set(SDL2_INCLUDE_DIRS ${SDL2_INCLUDE_DIR})
set(SDL2_LIBRARIES ${SDL2_LIBRARY})

include(FindPackageHandleStandardArgs)
FIND_PACKAGE_HANDLE_STANDARD_ARGS(SDL2 REQUIRED_VARS
	SDL2_INCLUDE_DIRS
	SDL2_LIBRARIES)
	
mark_as_advanced(SDL2_INCLUDE_DIR SDL2_LIBRARY)