find_library(SDL2_TTF_LIBRARY NAMES SDL2_ttf libSDL2_ttf)
find_path(SDL2_TTF_INCLUDE_DIR SDL2/SDL_ttf.h)
set(SDL2_TTF_LIBRARIES ${SDL2_TTF_LIBRARY})
set(SDL2_TTF_INCLUDE_DIRS ${SDL2_TTF_INCLUDE_DIR})

include(FindPackageHandleStandardArgs)
FIND_PACKAGE_HANDLE_STANDARD_ARGS(SDL2_ttf REQUIRED_VARS
	SDL2_TTF_LIBRARIES
	SDL2_TTF_INCLUDE_DIRS)
	
mark_as_advanced(SDL2_TTF_LIBRARY SDL2_TTF_INCLUDE_DIR)