find_path(ASSIMP_INCLUDE_DIR assimp/Importer.hpp)
find_library(ASSIMP_LIBRARY assimp libassimp)
set(ASSIMP_INCLUDE_DIRS ${ASSIMP_INCLUDE_DIR})
set(ASSIMP_LIBRARIES ${ASSIMP_LIBRARY})
  
FIND_PACKAGE_HANDLE_STANDARD_ARGS(Assimp REQUIRED_VARS
	ASSIMP_INCLUDE_DIRS
	ASSIMP_LIBRARIES)
	
mark_as_advanced(ASSIMP_INCLUDE_DIR ASSIMP_LIBRARY)