find_library(ASSIMP_LIBRARY assimp libassimp)
find_path(ASSIMP_INCLUDE_DIR assimp/Importer.hpp)
set(ASSIMP_LIBRARIES ${ASSIMP_LIBRARY})
set(ASSIMP_INCLUDE_DIRS ${ASSIMP_INCLUDE_DIR})

include(FindPackageHandleStandardArgs)
FIND_PACKAGE_HANDLE_STANDARD_ARGS(Assimp REQUIRED_VARS
	ASSIMP_LIBRARIES
	ASSIMP_INCLUDE_DIRS)
	
mark_as_advanced(ASSIMP_LIBRARY ASSIMP_INCLUDE_DIR)