release:
	cmake . -DCMAKE_BUILD_TYPE=Release && make

debug:
	cmake . -DCMAKE_BUILD_TYPE=Debug && make

launch:
	(cd ./bin; ./Demo)

clean:
	rm -rf Makefile
	rm -rf CMakeCache.txt cmake_install.cmake CMakeFiles
	rm -rf aclocal.m4 configure autom4te.cache compile config.guess config.sub depcomp install-sh ltmain.sh missing Makefile.in Demo/Makefile.in Engine/Makefile.in
