# Makefile for demo

CC= g++
NAME= Demo
DIR= bin/

CFLAGS= -std=c++11 -Wall -g -I../Engine/include -MMD -MP
LDFLAGS= -L../Engine/bin/ -lEngine -Wl,-rpath=../Engine/bin/

SRC= $(shell find src/ -name \*.cpp -print)
OBJ= $(SRC:%.cpp=obj/%.o)
DEP= $(SRC:%.cpp=obj/%.d)

all:	$(OBJ)
	$(CC) $^ -o $(DIR)$(NAME) $(LDFLAGS)

-include $(DEP)

obj/%.o:	%.cpp
	$(CC) $(CFLAGS) -c $< -o $@

clean:
	rm -f $(OBJ)
	rm -f $(DEP)
	rm -f *~
	rm -f src/*~
	rm -f $(DIR)$(NAME)
